[package]
name = "hashf"
version = "1.0.0"
authors = ["colvin <39858617+colvin@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4"
fern = "0.6"
chrono = "0.4"
md5 = "0.7"
sha1 = "0.6"
sha2 = "0.9"
